# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2

development:
  adapter: mysql2
  encoding: utf8
  database: sql_test_app
  username: root
  password: SzIndia!
  host: 127.0.0.1
  port: 3306